CC=g++

all: avg oddsevens findTerm palindrome reverse

avg: avg.cpp
	$(CC) -Wall -o avg avg.cpp

oddsevens: oddsevens.cpp
	$(CC) -Wall -o oddsevens oddsevens.cpp

findTerm: findTerm.cpp
	$(CC) -Wall -o findTerm findTerm.cpp

palindrome: palindrome.cpp
	$(CC) -Wall -o palindrome palindrome.cpp

reverse: reverse.cpp
	$(CC) -Wall -o reverse reverse.cpp

clean : 
	rm *.exe
