# Prima esercitazione

'''
Programma che valuta se un valore inserito dall'utente è uguale al valore definito dal programma
Guess number
'''

import random

# magic_number = 5
random_magic_number = random.randint(0, 9)
print("This is the autogenerated random value: ", random_magic_number)

# print(type(random_magic_number))
# print(type(magic_number))

print("Indovina il numero vincente")

# casting da str a int
user_number = int(input("Inserisci il numero: "))

# print("Il numero che hai inserito è:", user_number)
user_magic_number = user_number
# print(" ->", user_magic_number)
# print(type(user_magic_number))

# Checks if the number generated by random func is equals to
# the number geneated by us
isEquals = (user_magic_number == random_magic_number)
print(isEquals)

if(isEquals):
  print("Hai vinto!!!")
else:
  print("Mi dispiace hai perso!")